function buscaNacionalidad(pais) {
  
    const paises = [
        ['AFG','AF','Afganistán'],
        ['ALA','AX','Åland'],
        ['ALB','AL','Albania'],
        ['DEU','DE','Alemania'],
        ['AND','AD','Andorra'],
        ['AGO','AO','Angola'],
        ['AIA','AI','Anguila'],
        ['ATA','AQ','Antártida'],
        ['ATG','AG','Antigua y Barbuda'],
        ['ANT','AN','Antillas Neerlandesas'],
        ['SAU','SA','Arabia Saudita'],
        ['DZA','DZ','Argelia'],
        ['ARG','AR','Argentina'],
        ['ARM','AM','Armenia'],
        ['ABW','AW','Aruba'],
        ['AUS','AU','Australia'],
        ['AUT','AT','Austria'],
        ['AZE','AZ','Azerbaiyán'],
        ['BHS','BS','Bahamas'],
        ['BHR','BH','Bahréin'],
        ['BGD','BD','Bangladesh'],
        ['BRB','BB','Barbados'],
        ['BLR','BY','Bielorrusia'],
        ['BEL','BE','Bélgica'],
        ['BLZ','BZ','Belice'],
        ['BEN','BJ','Benín'],
        ['BMU','BM','Bermudas'],
        ['BTN','BT','Bután'],
        ['BOL','BO','Bolivia'],
        ['BIH','BA','Bosnia y Herzegovina'],
        ['BWA','BW','Botsuana'],
        ['BVT','BV','Isla Bouvet'],
        ['BRA','BR','Brasil'],
        ['BRN','BN','Brunéi'],
        ['BGR','BG','Bulgaria'],
        ['BFA','BF','Burkina Faso'],
        ['BDI','BI','Burundi'],
        ['CPV','CV','Cabo Verde'],
        ['CYM','KY','Islas Caimán'],
        ['KHM','KH','Camboya'],
        ['CMR','CM','Camerún'],
        ['CAN','CA','Canadá'],
        ['CAF','CF','República Centroafricana'],
        ['TCD','TD','Chad'],
        ['CZE','CZ','República Checa'],
        ['CHL','CL','Chile'],
        ['CHN','CN','China'],
        ['CYP','CY','Chipre'],
        ['CCK','CC','Islas Cocos'],
        ['COL','CO','Colombia'],
        ['COM','KM','Comoras'],
        ['COG','CG','República del Congo'],
        ['COD','CD','República Democrática del Congo'],
        ['COK','CK','Islas Cook'],
        ['PRK','KP','Corea del Norte'],
        ['KOR','KR','Corea del Sur'],
        ['CIV','CI','Costa de Marfil'],
        ['CRI','CR','Costa Rica'],
        ['HRV','HR','Croacia'],
        ['CUB','CU','Cuba'],
        ['DNK','DK','Dinamarca'],
        ['DMA','DM','Dominica'],
        ['DOM','DO','República Dominicana'],
        ['ECU','EC','Ecuador'],
        ['EGY','EG','Egipto'],
        ['SLV','SV','El Salvador'],
        ['ARE','AE','Emiratos Árabes Unidos'],
        ['ERI','ER','Eritrea'],
        ['SVK','SK','Eslovaquia'],
        ['SVN','SI','Eslovenia'],
        ['ESP','ES','España'],
        ['ESP','EA','España (Ceuta y Melilla)'],
        ['USA','US','Estados Unidos'],
        ['UMI','UM','Islas ultramarinas de Estados Unidos'],
        ['EST','EE','Estonia'],
        ['ETH','ET','Etiopía'],
        ['FRO','FO','Islas Feroe'],
        ['PHL','PH','Filipinas'],
        ['FIN','FI','Finlandia'],
        ['FJI','FJ','Fiyi'],
        ['FRA','FR','Francia'],
        ['GAB','GA','Gabón'],
        ['GMB','GM','Gambia'],
        ['GEO','GE','Georgia'],
        ['SGS','GS','Islas Georgias del Sur y Sandwich del SurGHA GH Ghana'],
        ['GIB','GI','Gibraltar'],
        ['GRD','GD','Granada'],
        ['GRC','GR','Grecia'],
        ['GRL','GL','Groenlandia'],
        ['GLP','GP','Guadalupe'],
        ['GUM','GU','Guam'],
        ['GTM','GT','Guatemala'],
        ['GUF','GF','Guayana Francesa'],
        ['GGY','GG','Guernsey'],
        ['GIN','GN','Guinea'],
        ['GNQ','GQ','Guinea Ecuatorial'],
        ['GNB','GW','Guinea-Bissau'],
        ['GUY','GY','Guyana'],
        ['HTI','HT','Haití'],
        ['HMD','HM','Islas Heard y McDonald'],
        ['HND','HN','Honduras'],
        ['HKG','HK','Hong Kong'],
        ['HUN','HU','Hungría'],
        ['IND','IN','India'],
        ['IDN','ID','Indonesia'],
        ['IRN','IR','Irán'],
        ['IRQ','IQ','Iraq'],
        ['IRL','IE','Irlanda'],
        ['ISL','IS','Islandia'],
        ['ISR','IL','Israel'],
        ['ITA','IT','Italia'],
        ['JAM','JM','Jamaica'],
        ['JPN','JP','Japón'],
        ['JEY','JE','Jersey'],
        ['JOR','JO','Jordania'],
        ['KAZ','KZ','Kazajistán'],
        ['KEN','KE','Kenia'],
        ['KGZ','KG','Kirguistán'],
        ['KIR','KI','Kiribati'],
        ['KWT','KW','Kuwait'],
        ['LAO','LA','Laos'],
        ['LSO','LS','Lesoto'],
        ['LVA','LV','Letonia'],
        ['LBN','LB','Líbano'],
        ['LBR','LR','Liberia'],
        ['LBY','LY','Libia'],
        ['LIE','LI','Liechtenstein'],
        ['LTU','LT','Lituania'],
        ['LUX','LU','Luxemburgo'],
        ['MAC','MO','Macao'],
        ['MKD','MK','ARY Macedonia'],
        ['MDG','MG','Madagascar'],
        ['MYS','MY','Malasia'],
        ['MWI','MW','Malawi'],
        ['MDV','MV','Maldivas'],
        ['MLI','ML','Malí'],
        ['MLT','MT','Malta'],
        ['FLK','FK','Islas Malvinas'],
        ['IMN','IM','Isla de Man'],
        ['MNP','MP','Islas Marianas del Norte'],
        ['MAR','MA','Marruecos'],
        ['MHL','MH','Islas Marshall'],
        ['MTQ','MQ','Martinica'],
        ['MUS','MU','Mauricio'],
        ['MRT','MR','Mauritania'],
        ['MYT','YT','Mayotte'],
        ['MEX','MX','México'],
        ['FSM','FM','Micronesia'],
        ['MDA','MD','Moldavia'],
        ['MCO','MC','Mónaco'],
        ['MNG','MN','Mongolia'],
        ['MNE','ME','Montenegro'],
        ['MSR','MS','Montserrat'],
        ['MOZ','MZ','Mozambique'],
        ['MMR','MM','Myanmar'],
        ['NAM','NA','Namibia'],
        ['NRU','NR','Nauru'],
        ['CXR','CX','Isla de Navidad'],
        ['NPL','NP','Nepal'],
        ['NIC','NI','Nicaragua'],
        ['NER','NE','Níger'],
        ['NGA','NG','Nigeria'],
        ['NIU','NU','Niue'],
        ['NFK','NF','Norfolk'],
        ['NOR','NO','Noruega'],
        ['NCL','NC','Nueva Caledonia'],
        ['NZL','NZ','Nueva Zelanda'],
        ['OMN','OM','Omán'],
        ['NLD','NL','Países Bajos'],
        ['PAK','PK','Pakistán'],
        ['PLW','PW','Palaos'],
        ['PSE','PS','Palestina (ANP)'],
        ['PAN','PA','Panamá'],
        ['PNG','PG','Papúa Nueva Guinea'],
        ['PRY','PY','Paraguay'],
        ['PER','PE','Perú'],
        ['PCN','PN','Islas Pitcairn'],
        ['PYF','PF','Polinesia Francesa'],
        ['POL','PL','Polonia'],
        ['PRT','PT','Portugal'],
        ['PRI','PR','Puerto Rico'],
        ['QAT','QA','Qatar'],
        ['GBR','GB','Reino Unido'],
        ['REU','RE','Reunión'],
        ['RWA','RW','Ruanda'],
        ['ROU','RO','Rumania'],
        ['RUS','RU','Rusia'],
        ['ESH','EH','Sahara Occidental'],
        ['SLB','SB','Islas Salomón'],
        ['WSM','WS','Samoa'],
        ['ASM','AS','Samoa Americana'],
        ['KNA','KN','San Cristóbal y Nieves'],
        ['SMR','SM','San Marino'],
        ['SPM','PM','San Pedro y Miquelón'],
        ['VCT','VC','San Vicente y las Granadinas'],
        ['SHN','SH','Santa Helena'],
        ['LCA','LC','Santa Lucía'],
        ['STP','ST','Santo Tomé y Príncipe'],
        ['SEN','SN','Senegal'],
        ['SRB','RS','Serbia'],
        ['SYC','SC','Seychelles'],
        ['SLE','SL','Sierra Leona'],
        ['SGP','SG','Singapur'],
        ['SYR','SY','Siria'],
        ['SOM','SO','Somalia'],
        ['LKA','LK','Sri Lanka'],
        ['SWZ','SZ','Suazilandia'],
        ['ZAF','ZA','Sudáfrica'],
        ['SDN','SD','Sudán'],
        ['SWE','SE','Suecia'],
        ['CHE','CH','Suiza'],
        ['SUR','SR','Surinam'],
        ['SJM','SJ','Svalbard y Jan Mayen'],
        ['THA','TH','Tailandia'],
        ['TWN','TW','Taiwán'],
        ['TZA','TZ','Tanzania'],
        ['TJK','TJ','Tayikistán'],
        ['IOT','IO','Territorio Británico del Océano Índico'],
        ['ATF','TF','Territorios Australes Franceses'],
        ['TLS','TL','Timor Oriental'],
        ['TGO','TG','Togo'],
        ['TKL','TK','Tokelau'],
        ['TON','TO','Tonga'],
        ['TTO','TT','Trinidad y Tobago'],
        ['TUN','TN','Túnez'],
        ['TCA','TC','Islas Turcas y Caicos'],
        ['TKM','TM','Turkmenistán'],
        ['TUR','TR','Turquía'],
        ['TUV','TV','Tuvalu'],
        ['UKR','UA','Ucrania'],
        ['UGA','UG','Uganda'],
        ['URY','UY','Uruguay'],
        ['UZB','UZ','Uzbekistán'],
        ['VUT','VU','Vanuatu'],
        ['VAT','VA','Ciudad del Vaticano'],
        ['VEN','VE','Venezuela'],
        ['VNM','VN','Vietnam'],
        ['VGB','VG','Islas Vírgenes Británicas'],
        ['VIR','VI','Islas Vírgenes Estadounidenses'],
        ['WLF','WF','Wallis y Futuna'],
        ['YEM','YE','Yemen'],
        ['DJI','DJ','Yibuti'],
        ['ZMB','ZM','Zambia'],
        ['ZWE','ZW','Zimbabue']
    ];

    //console.log(pais);
    const nlongitud = paises.length;

    for (var i = 0; i < nlongitud; i++) {
        if( paises[i][0] === pais ) {
            //console.log("entre el valor de pais nacionalidad");
            //console.log(paises[i][1]);
            return paises[i][1];
        }
    }
}

module.exports.buscaNacionalidad = buscaNacionalidad;